/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaLibrary;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Hello brother");
        return true;
    }
}
